name: Databricks CI/CD

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v4
      # Download the Databricks CLI. See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main
      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
        run: |
          databricks configure --host $DATABRICKS_HOST --client-id $DATABRICKS_CLIENT_ID --client-secret $DATABRICKS_CLIENT_SECRET --tenant-id $DATABRICKS_TENANT_ID
      - name: Validate on Databricks
        run: |
          databricks bundle validate
          databricks bundle deploy -t dev
          databricks bundle run validate_job
        working-directory: .
  
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.DATABRICKS_TENANT_ID }}
        run: |
          databricks configure --host $DATABRICKS_HOST --client-id $DATABRICKS_CLIENT_ID --client-secret $DATABRICKS_CLIENT_SECRET --tenant-id $DATABRICKS_TENANT_ID
      - name: Deploy to Databricks Prod
        run: |
          databricks bundle deploy -t prod
          databricks bundle run prod_job
        working-directory: .